### ISSUE TITLE
Is wrapStore still needed

### ISSUE THREAD

**Issue by spookyuser** [StyleT/webext-pegasus#5]
https://github.com/StyleT/webext-pegasus/blob/e3f19980efb3ca1b501f5b21414e7d87dbaaa80c/packages/store-zustand/README.md?plain=1#L21C1-L52C4

Doesn't seem like the import is used in this example.

**Comment by StyleT** [comment]
Hi! It shouldn't be needed. I'll take a closer look tomorrow

**Comment by spookyuser** [comment]
Thanks, pretty sure it's not needed I'm not using it and works great, awesome library!

**Comment by StyleT** [comment]
Published as `v0.3.6`. Thanks for your contribution!
